# Git
alias g='git'
alias cl='g cl'
alias st='g st'
alias ad='g ad'
alias cm='g cm'
alias co='g co'
alias br='g br'
alias lg='g lg'
alias gr='g gr'
alias lgn='g lgn'
alias addi='g addi'
alias adi='g adi'
alias diff='g diff'
alias diffs='diff --staged'
alias up='g up'
alias pull='g pull'
alias push='g push'
